name: Deploy Terraform + Python App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Debug Terraform State
      run: |
        echo "==== TERRAFORM STATE ===="
        terraform state list || true

        echo "==== TERRAFORM OUTPUTS ===="
        terraform output || true

#    - name: Get Web App Name
#      id: tfoutput
#      run: |
#        WEBAPP_NAME=$(terraform output -raw webapp_name | tr -d '\r' | head -n 1)
#        echo "WEBAPP_NAME=$WEBAPP_NAME" >> $GITHUB_ENV

    - name: Deploy App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tf-python-app-5zrg6iviyu
        package: ./app/src
